insert into item values(1, 'Galaxy S9', 'Samsung', 'Smartphones', 1000);
insert into item values(2, 'Galaxy Fold', 'Samsung', 'Smartphones', 2000);
insert into item values(3, '27 ES FHD', 'HP', 'Monitors', 300);
insert into item values(4, 'iPhone XS', 'Apple', 'Smartphones', 1800);
insert into item values(5, 'Charge 4', 'JBL', 'Speakers', 200);
insert into item values(6, 'Infinity Display 65', 'LG', 'Monitors', 5000);
insert into item values(7, 'Mate 20 Pro', 'Huawei', 'Smartphones', 1500);
insert into item values(8, 'Megaboom', 'Ultimate Ears', 'Speakers', 300);
insert into item values(9, 'SoundSport Wireless', 'Bose', 'Earphones', 140);
insert into item values(10, 'All-in-One PC', 'Dell', 'Desktops', 800);